[manager]

prepend_keymap = [
	{ on = [ "<C-w>" ], 		run = "close",              desc = "Close the current tab, or quit if it is last tab" },
	{ on = [ "p", "p" ],    run = "paste",              desc = "Paste the files" },
	{ on = [ "p", "P" ],    run = "paste --force",      desc = "Paste the files (overwrite if the destination exists)" },
	{ on = [ "p", "s" ],    run = "link",               desc = "Symlink the absolute path of files" },
	{ on = [ "p", "S" ],    run = "link --relative",    desc = "Symlink the relative path of files" },
	{ on = [ "F" ],         run = "jump fzf",           desc = "Jump to a directory, or reveal a file using fzf" },
	{ on = [ "z" ],         run = "plugin z.lua",       desc = "Jump to a directory using z.lua" },
	{ on = [ "?" ],         run = "help",               desc = "Open help" },
]

[tasks]

prepend_keymap = [
	{ on = [ "?" ], run = "help", desc = "Open help" },
]

[select]

prepend_keymap = [
	{ on = [ "?" ], run = "help", desc = "Open help" },
]

[input]

prepend_keymap = [
	{ on = [ "?" ], run = "help", desc = "Open help" },
]

[completion]

prepend_keymap = [
	{ on = [ "?" ], run = "help", desc = "Open help" },
]
