[manager]
ratio = [2, 3, 4]
linemode = "mtime"
show_hidden = true
sort_dir_first = true
show_symlink = true

[preview]
image_quality = 90
max_width = 1080
max_height = 1920

[opener]
extract = [{ run = 'ouch d -y "$@"', desc = "Extract here", for = "unix" }]

[open]
prepend_rules = [
	{ mime = "application/x-xz", use = [
		"extract",
		"reveal",
	] },
	{ mime = "application/gentoo.*", use = [
		"edit",
		"reveal",
	] },
]

[plugin]
prepend_previewers = [
	# Archive previewer
	{ mime = "application/{*zip,tar,bzip2,7z-compressed,rar,xz}", run = "ouch" },
	{ mime = "application/gentoo.*", run = "code" },
]
append_previewers = [{ name = "*", run = "hexyl" }]

[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"
