[manager]
ratio          = [1, 3, 4]
linemode        = "mtime"
show_hidden     = true

[opener]
extract = [
	{ run = 'ouch d "$1" --yes', desc = "Extract here", for = "unix" },
]

[open]
prepend_rules = [
	{ mime = "application/x-xz", use = [ "extract", "reveal" ] },
	{ mime = "application/vnd.gentoo.*", use = [ "edit", "reveal" ] },
]

[plugin]
prepend_previewers = [
	{ mime = "application/x-xz",            run = "archive" },
	{ mime = "application/vnd.gentoo.*", 		run = "code" },
]
append_previewers = [
  { name = "*", 													run = "hexyl" },
]
