[manager]
ratio          = [1, 3, 4]
linemode        = "mtime"
show_hidden     = true

[preview]
max_width       = 1200
max_height      = 700
image_filter    = "lanczos3"
image_quality   = 90
sixel_fraction  = 10
