layerrule = no_anim on, match:namespace wallpaper
layerrule = no_anim on, match:namespace panel
layerrule = blur on, match:namespace launcher
layerrule = ignore_alpha 0, match:namespace launcher
layerrule = blur on, match:namespace notifications
