color:
  red: &red f92672ff
  green: &green a6e22eff
  yellow: &yellow e6db74ff
  orange: &orange fd971fff
  purple: &purple ae81ffff
  blue: &blue 66d9efff
  write: &write f8f8f2ff
  black: &black 222222ff
  gray: &gray a9a9b3ff

  prompt_color: &prompt_color f8f8f2ff

delimiter_str: &delimiter_str
  string: {text: "┃", foreground: 444444ff}

delimiter: &delimiter
  label:
    content:
      *delimiter_str

prompt_font: &prompt_font "UbuntuMono Nerd Font:style=bold:size=32"

bar:
  height: 32
  location: top
  layer: top
  monitor: eDP-1
  background: 00000000
  foreground: *write
  margin: 20
  spacing: 8
  font: "UbuntuMono Nerd Font:size=28"

  left:

    - label:
        content:
          string: {text: cpu, foreground: *prompt_color, font: *prompt_font}
    - cpu:
        poll-interval: 1000
        content:
          map:
            conditions:
              id < 0:
                map:
                  default:
                    - string: {text: "{cpu}%"}
                  conditions:
                    cpu >= 90:
                      - string: {text: "{cpu}%", foreground: *red}

    - *delimiter

    - label:
        content:
          string: {text: mem, foreground: *prompt_color, font: *prompt_font}
    - mem:
        poll-interval: 1000
        content:
          map:
            default:
              - string: {text: "{percent_used}%"}
            conditions:
              percent_used >= 80:
                - string: {text: "{percent_used}%", foreground: *red}
              percent_used >= 60:
                - string: {text: "{percent_used}%", foreground: *yellow}

    - network:
        poll-interval: 1000
        content:
          map:
            default: {empty: {}}
            conditions:
              name == enp0s31f6:
                map:
                  default: {empty: {}}
                  conditions:
                    state == up && ipv4 != "":
                    - *delimiter_str

    - network:
        poll-interval: 1000
        content:
          map:
            default: {empty: {}}
            conditions:
              name == enp0s31f6:
                map:
                  default: {empty: {}}
                  conditions:
                    state == up && ipv4 != "":
                    - string: {text: "eth", foreground: *prompt_color, font: *prompt_font}

    - network:
        poll-interval: 1000
        content:
          map:
            default: {empty: {}}
            conditions:
              name == enp0s31f6:
                map:
                  default: {empty: {}}
                  conditions:
                    state == up && ipv4 != "":
                    - string: {text: "{dl-speed:mb}"}

    - network:
        poll-interval: 1000
        content:
          map:
            default: {empty: {}}
            conditions:
              name == enp0s31f6:
                map:
                  default: {empty: {}}
                  conditions:
                    state == up && ipv4 != "":
                    - string: {text: "{ul-speed:mb}"}
                    
    - network:
        poll-interval: 1000
        content:
          map:
            default: {empty: {}}
            conditions:
              name == wlan0:
                map:
                  default: {empty: {}}
                  conditions:
                    state == up && ipv4 != "":
                    - *delimiter_str

    - network:
        poll-interval: 1000
        content:
          map:
            default: {empty: {}}
            conditions:
              name == wlan0:
                map:
                  default: {empty: {}}
                  conditions:
                    state == up && ipv4 != "":
                    - string: {text: "wlan", foreground: *prompt_color, font: *prompt_font}

    - network:
        poll-interval: 1000
        content:
          map:
            default: {empty: {}}
            conditions:
              name == wlan0:
                map:
                  default: {empty: {}}
                  conditions:
                    state == up && ipv4 != "":
                    - string: {text: "{ssid}"}

    - network:
        poll-interval: 1000
        content:
          map:
            default: {empty: {}}
            conditions:
              name == wlan0:
                map:
                  default: {empty: {}}
                  conditions:
                    state == up && ipv4 != "":
                    - string: {text: "{dl-speed:mb}"}

    - network:
        poll-interval: 1000
        content:
          map:
            default: {empty: {}}
            conditions:
              name == wlan0:
                map:
                  default: {empty: {}}
                  conditions:
                    state == up && ipv4 != "":
                    - string: {text: "{ul-speed:mb}"}

  center:
    - clock:
        time-format: "%H:%M:%S"
        date-format: "%b %d %a"
        content:
          string: {text: "{date}  {time}", font: "UbuntuMono Nerd Font:size=32"}


  right:

    - label:
        content:
          string: {text: mic, foreground: *prompt_color, font: *prompt_font}
    - pipewire:
        content:
          map:
            conditions:
              type == "source":
                map:
                  default:
                    - string: {text: "{cubic_volume}%"}
                  conditions:
                    muted:
                      - string: {text: "mute", foreground: *gray}
                    cubic_volume == 0:
                      - string: {text: "0%", foreground: *gray}
                    cubic_volume > 100:
                      - string: {text: "{cubic_volume}%", foreground: *yellow}

    - *delimiter

    - label:
        content:
          string: {text: vol, foreground: *prompt_color, font: *prompt_font}
    - pipewire:
        content:
          map:
            conditions:
              type == "sink":
                map:
                  default:
                    - string: {text: "{cubic_volume}%"}
                  conditions:
                    muted:
                      - string: {text: "mute", foreground: *gray}
                    cubic_volume == 0:
                      - string: {text: "0%", foreground: *gray}
                    cubic_volume > 100:
                      - string: {text: "{cubic_volume}%", foreground: *yellow}

    - *delimiter

    - label:
        content:
          string: {text: bri, foreground: *prompt_color, font: *prompt_font}
    - backlight:
        name: intel_backlight
        content:
          - string: {text: "{percent}%"}

    - *delimiter

    - label:
        content:
          string: {text: bat, foreground: *prompt_color, font: *prompt_font}
    - battery:
        name: BAT0
        poll-interval: 10000
        content:
          map:
            default:
              map:
                default:
                  - string: {text: "{capacity}%"}
                conditions:
                  capacity < 10:
                    - string: {text: "{capacity}%", foreground: *red}
                  capacity <= 30:
                    - string: {text: "{capacity}%", foreground: *red}
                  capacity <= 60:
                    - string: {text: "{capacity}%", foreground: *yellow}
            conditions:
              state == charging:
                - string: {text: "{capacity}%", foreground: *green}
